services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: always
    networks:
      - app_network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "postgresql_data:/bitnami/postgresql"

volumes:
  postgresql_data:

networks:
  app_network: